# DO NOT SIMPLY COPY AND PASTE THIS CONFIGURATION FILE!
# It is a reference for the default configuration. The correct way to
# do it is to ONLY include the values in your configuration that you
# want to override.

# Configuration syntax is YAML, learn more at: https://yaml.org


##########################################################
# Backend settings.
##########################################################
# The backend the shell should use, one of: browser, api
backend: api
# The database connection string, in a format SQLAlchemy understands.
# DO NOT USE THE LINE AS IT IS WRITTEN BELOW, IT ONLY ILLUSTRATES THE DEFAULT LOCATION.
# database: sqlite:////home/[username]/.local/share/chatgpt-wrapper/profiles/default/storage.db


##########################################################
# Shell settings.
##########################################################
shell:
  # NOTE: This setting is only available on the following backends: api
  # Customize the prompt prefix, the following token are available:
  # - $SYSTEM_MESSAGE_ALIAS: The current your system message alias
  # - $USER: Logged in username
  # - $MODEL: The LLM model name
  # - $PRESET_OR_MODEL: The active preset if set, or the LLM model name
  # - $NEWLINE: Insert a newline
  # - $TEMPERATURE: The current temperature
  # - $MAX_SUBMISSION_TOKENS: The maximum number of tokens in a submission
  # - $CURRENT_CONVERSATION_TOKENS: The token count of the current conversation (only supported for chat models)
  prompt_prefix: '($TEMPERATURE/$MAX_SUBMISSION_TOKENS/$CURRENT_CONVERSATION_TOKENS): $SYSTEM_MESSAGE_ALIAS$NEWLINE$USER@$PRESET_OR_MODEL'
  # Full path to the file that stores a history of commands in the shell.
  # Set to false to disable storing history.
  history_file: /tmp/repl_history.log


##########################################################
# Browser settings.
##########################################################
# NOTE: These settings only work on the following backends: browser
browser:
  # Enable debug mode (shows browser window if true, headless if false)
  debug: false
  # The browser to use, one of: firefox, chromium, webkit
  provider: firefox


##########################################################
# Model settings.
##########################################################
model:
  # The preset to use on startup.
  # See '/help presets' for more information.
  default_preset: null
  # If true, responses will be streamed in real time (no markdown formatting).
  # By default, streaming is enabled in the REPL for supported providers, and
  # disabled otherwise.
  streaming: true
  # Configure aliases to switch between system messages, key is alias, value is message.
  # NOTE: This setting only works on the following backend: api
  # NOTE: This setting is only active for chat models.
  # See '/help system_message' for more information.
  system_message:
    programmer: "You are an expert programmer, who responds to questions with brief examples in code."


##########################################################
# Chat settings.
##########################################################
chat:
  # Chat logs.
  log:
    # Enable logging to a file.
    enabled: false
    # Full path to the log file.
    filepath: chatgpt.log


##########################################################
# Log settings.
##########################################################
log:
  # Console logging.
  console:
    # Message format.
    format: '%(name)s - %(levelname)s - %(message)s'
    # Message level (must be valid Python logging module level).
    level: ERROR


##########################################################
# Plugin settings.
# See the README for more informaiton on plugins.
##########################################################
plugins:
  enabled:
    # Core plugins, see README for more details.
    - echo
    #- awesome
    #- database
    #- data_query
    #- shell
    #- zap
    # Core provider plugins, see README for more details.
    #- provider_ai21
    #- provider_cohere
    #- provider_huggingface_hub
    #- provider_openai

##########################################################
# Debug settings.
##########################################################
debug:
  # Debug logging.
  log:
    # Enable to log debug messages.
    enabled: false
    # Full path to the log file.
    filepath: /tmp/chatgpt-debug.log
    # Message format.
    format: '%(name)s - %(asctime)s - %(levelname)s - %(message)s'
    # Message level (must be valid Python logging module level).
    level: DEBUG
