version: '3.9'
services:
  llm-workflow-engine:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lwe-container
    # restart: always
    volumes:
      - ./:/src
      - ./tmp:/tmp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EDITOR=vim
    ports:
      - 5000:5000 # Flask port
    command: "bash /src/docker-entrypoint.sh" # Run the entrypoint script
